todolist/temdie/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name='login'),
    path('updatestatus/<int:task_id>/', views.updatestatus, name='update_status'),
    path('addtask/<int:user_id>/', views.addtask, name='add_task'),
    path('deletetask/<int:task_id>/', views.deletetask, name='delete_task'),
    path('addtag/', views.addtag, name='add_tag'),
    path('updateprofile/<int:user_id>/', views.updateprofile, name='update_profile'),
    path('updateprofile/', views.updateprofile, name='update_profile'),
] 

todolist/todolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('temdie/', include('temdie.urls')) 
]

todolist/temdie/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=100)

    def __str__(self):
        return self.email

class TemdieTask(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    due_date = models.DateField()
    completed = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    

    def __str__(self):
        return self.title
    
class TemdieTag(models.Model):
    name = models.CharField(max_length=50)
    task = models.ManyToManyField(TemdieTask)

    def __str__(self):
        return self.name
    
    

todolist/temdie/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from django.contrib import messages
from django.http import JsonResponse
# Create your views here.

def signup(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        password = request.POST['password']

        
        if User.objects.filter(email=email).exists():
                messages.info(request, 'email already exist!')
                return render(request, 'register.html')
        else:
                user =  User.objects.create(name=name, email=email, password=password)
                user.save()
                messages.info(request, 'User created succesfully!')
                return render(request, 'login.html')
    else:

      return render(request, 'register.html')

def login(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        user = User.objects.get(email=email)
        tags = TemdieTag.objects.filter(task__user=user)  
        tasks = user.temdietask_set.all()  

        if user.password == password:
            tags = TemdieTag.objects.filter(task__user=user)  
            tasks = user.temdietask_set.all() 
            context = {
            'user': user,
            'tags': tags,
            'tasks': tasks
            }

            return render(request, 'home.html', context)
        
        else:
             return render(request, 'result.html', {'result': "Invalid email or password"})
            
    else:
        return render(request, 'login.html')

def updatestatus(request, task_id):
    task = TemdieTask.objects.get(id=task_id)
    task.completed = True
    task.save()
    return render(request, 'result.html', {'result': "Task status updated to complete"})

def addtask(request, user_id):
        title = request.POST['title']
        desc = request.POST['description']
        due_date = request.POST['due_date']
        user = get_object_or_404(User, id=user_id)

        if TemdieTask.objects.filter(title=title).exists():
                return render(request, 'result.html', {'result': "This title already exist"})
        else:
                task =  TemdieTask.objects.create(title=title, description=desc, due_date=due_date, user=user)
                task.save()
                return render(request, 'result.html', {'result': "Task added !!"})        

def addtag(request):
    name = request.POST['name']
    task_ids = request.POST.getlist('tasks')

    task_ids = [int(task_id) for task_id in task_ids if task_id.isdigit()]

    tag = TemdieTag.objects.create(name=name)
    
    for task_id in task_ids:
        task = TemdieTask.objects.get(id=task_id)
        tag.task.add(task)

    return render(request, 'result.html', {'result': "Tag added !!"})

def deletetask(request, task_id):
    task = TemdieTask.objects.get(id=task_id)
    task.delete()

    return render(request, 'result.html', {'result': "Task deleted !!"})

def updateprofile(request, user_id):

    if request.method == 'POST':
        user = User.objects.get(id=user_id)

        user.name = request.POST['name']
        user.email = request.POST['email']
        user.password = request.POST['password']

        user.save()
        return render(request, 'result.html', {'result': "Fields updated !!"})

    else:
        user = User.objects.get(id=user_id)
        return render(request, 'updateprofile.html', {'user': user})

todolist/temdie/templates/home.html
<!DOCTYPE html>
<html>
<head>
    <title>Data Display Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1>Welcome {{user.name}} </h1>

        <h3>Task</h3>
        <button type="button" class="btn btn-primary mb-3" data-bs-toggle="modal" data-bs-target="#addTask">Add Task</button>
        <button type="button" class="btn btn-primary mb-3" data-bs-toggle="modal" data-bs-target="#addTag">Add Tag</button>
        <a href="{% url 'update_profile' user.id %}" class="btn btn-primary mb-3">Update profile</a>
    <br></br>
        <table class="table">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Due Date</th>
                    <th>Completed</th>
                    <th>Tags</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for task in tasks %}
                <tr>
                    <td>{{ task.title }}</td>
                    <td>{{ task.description }}</td>
                    <td>{{ task.due_date }}</td>
                    <td>
                    {% if task.completed %}
                            True
                        {% else %}
                            <form method="POST" action="{% url 'update_status' task.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary">Complete</button>
                            </form>
                        {% endif %}
                    </td>
                    <td>
                        <select>
                        {% for tag in task.temdietag_set.all %}
                        <option {% if tag.selected %}selected{% endif %}>{{ tag.name }}</option>
                        {% endfor %}
                        </select>
                    </td>
                    <td>
                        
                        <a href="{% url 'delete_task' task.id %}" class="btn btn-danger btn-sm" >Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <h3>Tag</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Tag</th>
                    <th>Tasks</th>
                </tr>
            </thead>
            <tbody>
                {% for tag in tags %}
                <td>{{ tag.name }}</td>

                <td>{{ tag.name }}</td>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="modal fade" id="addTask" tabindex="-1" aria-labelledby="addTask" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="addTask">Add Task</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">X</button>
                </div>
                <div class="modal-body">
                   
                    <form id="addPackageForm" method="post" action="{% url 'add_task' user.id %}">
                        {% csrf_token %}
                        
                        <div class="form-group">
                            <label for="taskTitle">Title</label>
                            <input type="text" class="form-control" id="taskTitle" name="title" placeholder="Enter task title">
                        </div>
                        <div class="form-group">
                            <label for="taskDescription">Description</label>
                            <textarea class="form-control" id="taskDescription" name="description" placeholder="Enter task description"></textarea>
                        </div>
                        <div class="form-group">
                            <label for="taskDueDate">Due Date</label>
                            <input type="date" class="form-control" id="taskDueDate" name="due_date">
                        </div>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>


    <div class="modal fade" id="addTag" tabindex="-1" aria-labelledby="addTag" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="addTag">Add Tag</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">X</button>
                </div>
                <div class="modal-body">
                   
                    <form id="addPackageForm" method="post" action="{% url 'add_tag' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="tagName">Tag Name</label>
                            <input type="text" class="form-control" id="tagName" name="name" placeholder="Enter tag name">
                          </div>
                          <div class="form-group">
                            <label for="tagTasks">Associated Tasks</label>
                            {% for task in tasks %}
                              <div class="form-check">
                                <input class="form-check-input" type="checkbox" name="tasks" value="{{ task.id }}">
                                <label class="form-check-label" for="task{{ task.id }}">
                                  {{ task.title }}
                                </label>
                              </div>
                            {% endfor %}
                          </div>
                          
                          <button type="submit" class="btn btn-primary">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

todolist/temdie/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Login and Registration Forms</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <div class="row"> 
            <div class="col-md-6">
                <h2>Login</h2>
                <form method="POST" action="{% url 'login' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="loginEmail">Email</label>
                        <input type="email" class="form-control" id="loginEmail" placeholder="Enter email" name="email">
                    </div>
                    <div class="form-group">
                        <label for="loginPassword">Password</label>
                        <input type="password" name="password" class="form-control" id="loginPassword" placeholder="Enter password">
                    </div>
                    <button type="submit" class="btn btn-primary">Login</button>
                    <p>Please <a href="{% url 'signup' %}">click here</a> to go to the register page.</p>
                </form>
            </div>
</body>
</html>

todolist/temdie/templates/register.html
<!DOCTYPE html>
<html>
<head>
    <title>Login and Registration Forms</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2>Register</h2>
                <form>
                    <div class="form-group">
                        <label for="Name">Name</label>
                        <input type="text" class="form-control" id="Name" placeholder="Enter name" name="name">
                    </div>
                    <div class="form-group">
                        <label for="Email">Email</label>
                        <input type="email" class="form-control" id="Email" placeholder="Enter email" name="email">
                    </div>
                    <div class="form-group">
                        <label for="Password">Password</label>
                        <input type="password" class="form-control" id="Password" placeholder="Enter password" password="password">
                    </div>
                    <button type="submit" class="btn btn-primary">Register</button>
                    <p>Please <a href="{% url 'login' %}">click here</a> to go to the login page.</p>
                </form>
            </div>
</body>
</html>

todolist/temdie/templates/result.html
<!DOCTYPE html>
<html>
<head>
    <title>Success Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3 success-message">
                <div class="alert alert-success" role="alert">
                    <strong>{{result}}</strong>
                </div>
            </div>
        </div>
    </div>
    
</body>
</html>

todolist/temdie/templates/updateprofile.html
<!DOCTYPE html>
<html>
<head>
    <title>Login and Registration Forms</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2>Update your profile</h2>
                <form method="post" action="{% url 'update_profile' user.id%}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="Name">Name</label>
                        <input type="text" class="form-control" id="Name" placeholder="Enter name" name="name" value="{{user.name}}">
                    </div>
                    <div class="form-group">
                        <label for="Email">Email</label>
                        <input type="email" class="form-control" id="Email" placeholder="Enter email" name="email" value="{{user.email}}">
                    </div>
                    <div class="form-group">
                        <label for="Password">Password</label>
                        <input type="text" class="form-control" id="Password" placeholder="Enter password" name="password" password="password" value="{{user.password}}">
                    </div>
                    <button type="submit" class="btn btn-primary">Save</button>
                </form>
            </div>
</body>
</html>